# -*- coding: utf-8 -*-
"""Copia de Aplicación Web para el Análisis del Índice KCDI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BeVZcZtoN0U6fZ33VbrNitr728wQWY0
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
==============================================================================
Aplicación Web para Análisis del Índice KCDI
Análisis de Justicia Epistémica en Bases de Datos de Scopus
===============
"""
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import warnings
import gender_guesser.detector as gender
from country_converter import convert

# ==============================================================================
# Funciones de procesamiento de datos y cálculo (basadas en tu script)
# ==============================================================================

@st.cache_data
def load_and_process_data(uploaded_file):
    """Carga y preprocesa el archivo de Scopus."""
    try:
        # Intenta leer el archivo como CSV o Excel
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file, encoding='utf-8')
        else:
            df = pd.read_excel(uploaded_file)
    except Exception as e:
        st.error(f"Error al leer el archivo. Asegúrate de que es un CSV o XLSX válido: {e}")
        return None

    # Verifica que las columnas necesarias existan
    if 'Authors' not in df.columns or 'Country' not in df.columns:
        st.error("El archivo debe contener las columnas 'Authors' y 'Country'.")
        return None

    # Limpieza y preparación inicial: se toma solo el autor principal.
    df['Authors'] = df['Authors'].str.split(';').str[0].str.strip()
    df.dropna(subset=['Authors', 'Country'], inplace=True)
    df = df[df['Authors'] != '']
    df = df[df['Country'] != '']

    # Inferencia de género del autor principal
    d = gender.Detector(case_sensitive=False)
    df['inferred_gender'] = df['Authors'].apply(lambda x: d.get_gender(str(x).split()[0].replace('-', '')))

    # Inferencia de la clasificación Norte/Sur Global a partir del país
    def get_global_south_status(country):
        if pd.isna(country) or not isinstance(country, str):
            return 'Unknown'
        country_name = convert(names=country, to='name_short', not_found=None)
        if country_name is None:
            return 'Unknown'
        continent = convert(names=country_name, to='continent', not_found=None)
        if continent is None:
            return 'Unknown'

        # Clasificación simplificada (ajustada para el contexto)
        north_global_continents = ['North America', 'Europe', 'Australia']
        return 'Sur Global' if continent not in north_global_continents else 'Norte Global'

    df['global_south_status'] = df['Country'].apply(get_global_south_status)

    # Combinación de variables para crear grupos interseccionales
    df['group'] = df['inferred_gender'] + ' - ' + df['global_south_status']

    return df

@st.cache_data
def calculate_kcdi(df):
    """Calcula el KCDI y las métricas asociadas."""
    total_contributions = len(df)
    if total_contributions == 0:
        return None, None, None, None

    group_counts = df['group'].value_counts()
    pi = group_counts / total_contributions

    # Cálculo del Índice de Shannon
    H_shannon = -np.sum(pi * np.log(pi.replace(0, 1)))

    # Asignación y Justificación de las Ponderaciones (Wi)
    # Estos valores pueden ser ajustados por el investigador.
    group_weights = {
        'female - Sur Global': 1.5,
        'male - Sur Global': 1.2,
        'female - Norte Global': 1.0,
        'male - Norte Global': 0.8,
        'mostly_female - Sur Global': 1.4,
        'mostly_male - Sur Global': 1.1,
        'mostly_female - Norte Global': 0.9,
        'mostly_male - Norte Global': 0.9,
        'unknown - Sur Global': 1.0,
        'unknown - Norte Global': 1.0,
        'andy - Sur Global': 1.0,
        'andy - Norte Global': 1.0,
        'unknown - Unknown': 1.0,
        'andy - Unknown': 1.0,
        'female - Unknown': 1.0,
        'male - Unknown': 1.0
    }

    df['Wi'] = df['group'].apply(lambda x: group_weights.get(x, 1.0))
    W_bar = df['Wi'].mean()

    # Cálculo del Índice KCDI
    kcdi = H_shannon * W_bar

    return kcdi, H_shannon, W_bar, df

def create_kcdi_compass_plot(kcdi_value):
    """Genera una visualización de tipo 'brújula' para el Índice KCDI."""
    warnings.filterwarnings("ignore", category=UserWarning)
    color_less_diverse = '#E34234'
    color_more_diverse = '#007FFF'
    label_font = {'fontweight': 'bold', 'fontsize': 10}
    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw={'projection': 'polar'})
    ax.set_theta_zero_location('W', offset=10)
    ax.set_theta_direction(-1)
    ax.set_yticklabels([])
    ax.set_xticks(np.deg2rad(np.arange(0, 181, 15)))
    ax.set_xticklabels([])
    ax.set_ylim(0, 1)
    ax.bar(np.deg2rad(np.arange(0, 91, 1)), height=1, width=np.deg2rad(1), bottom=0.8,
           color=color_less_diverse, alpha=0.8, label='Menos Diverso', zorder=1)
    ax.bar(np.deg2rad(np.arange(90, 181, 1)), height=1, width=np.deg2rad(1), bottom=0.8,
           color=color_more_diverse, alpha=0.8, label='Más Diverso', zorder=1)
    ax.text(np.deg2rad(180), 1.05, '0', ha='center', va='center', **label_font)
    ax.text(np.deg2rad(90), 1.05, '0.5', ha='center', va='center', **label_font)
    ax.text(np.deg2rad(0), 1.05, '1', ha='center', va='center', **label_font)
    ax.plot([np.deg2rad(180 * (1 - kcdi_value)), np.deg2rad(180 * (1 - kcdi_value))], [0, 0.9],
            color='black', linewidth=3, solid_capstyle='round', zorder=2)
    ax.scatter(np.deg2rad(180 * (1 - kcdi_value)), 0.9, color='black', s=100, zorder=2)
    ax.set_title(f'Índice KCDI: {kcdi_value:.3f}', fontsize=14, pad=20, fontweight='bold')
    ax.text(np.deg2rad(135), 0.5, 'Menos diverso', ha='center', va='center', **label_font, color='white')
    ax.text(np.deg2rad(45), 0.5, 'Más diverso', ha='center', va='center', **label_font, color='white')
    ax.spines['polar'].set_visible(False)
    ax.grid(False)
    plt.tight_layout()
    return fig

# ==============================================================================
# Lógica principal de la aplicación
# ==============================================================================
st.set_page_config(layout="wide")
st.title('Análisis de Justicia Epistémica: Índice KCDI')

st.markdown("""
Esta aplicación permite analizar la **diversidad de contribución al conocimiento** (KCDI) a partir de datos de Scopus.
Sube un archivo `.csv` o `.xlsx` que contenga los campos `Authors` y `Country`.
""")

uploaded_file = st.file_uploader("Sube tu archivo de Scopus", type=["csv", "xlsx"])

if uploaded_file:
    df_processed = load_and_process_data(uploaded_file)

    if df_processed is not None:
        st.write("✅ Datos cargados y procesados correctamente.")

        kcdi, H_shannon, W_bar, df_final = calculate_kcdi(df_processed)

        if kcdi is not None:
            # Sección de resultados
            st.markdown("---")
            st.subheader("📊 Resultados del Análisis KCDI")

            col1, col2 = st.columns([1, 2])
            with col1:
                st.metric(label="Índice KCDI", value=f"{kcdi:.4f}")
               st.info("El KCDI se calcula como: $H_{Shannon} \\times \\bar{W}$")
                st.metric(label="Índice de Shannon ($H_{Shannon}$)", value=f"{H_shannon:.4f}")
                st.metric(label="Factor de Ponderación ($\bar{W}$)", value=f"{W_bar:.4f}")
            with col2:
                st.pyplot(create_kcdi_compass_plot(kcdi))

            st.markdown("---")
            st.subheader("🔍 Análisis Interseccional y Visualizaciones")

            gender_region_counts = df_final['group'].value_counts().reset_index()
            gender_region_counts.columns = ['Grupo', 'Cantidad']
            fig_intersec = px.bar(gender_region_counts, x='Grupo', y='Cantidad', color='Grupo', title='Contribuciones Interseccionales (Género x Región)')
            st.plotly_chart(fig_intersec)

            st.markdown("---")
            st.subheader("📦 Exportación de Resultados")
            csv_data = df_final.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="Descargar datos procesados (CSV)",
                data=csv_data,
                file_name='scopus_data_processed.csv',
                mime='text/csv',
            )
